args:
  mode: inference
  i2v_encode_video: True
  latent_channels: 16
  load: "/opensource/SCAIL-Preview/mp_rank_00_model_states.pt"
  batch_size: 1
  input_type: cli
  sampling_image_size: [512, 896]
  vae_compress_size: [4, 8, 8] # t h w
  bf16: True
  sampling_fps: 16
  force_inference: True
  sequence_parallel_size: 1
  image2video: True
  use_i2v_clip: True
  use_pose: True
  representation: 'smpl_downsample'
  save_tag: official
